source 'https://cdn.cocoapods.org/'
source 'https://git.cm.eveus.com/Camera/waylens-fapp-CocoaPods-iOS.git'



platform :ios, '12.0'

use_frameworks!

workspace 'Acht'

def pods
  pod 'SwiftAlertView', '~> 2.2.1'
  pod 'BMPlayer/CacheSupport', :git => 'https://github.com/BrikerMan/BMPlayer.git'
  
  pod 'Firebase/Core', '~>10.10.0'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  
  pod 'AFNetworking'
  pod 'DropDown'
  pod 'JPush'
  pod 'ExpandableCell'
  pod 'CocoaAsyncSocket'
  pod 'Alamofire', '~> 4.0'
  pod 'KeychainAccess'
  pod 'Whisper'
  #pod 'Mixpanel-swift',       '~> 2.3'
  #pod 'Mixpanel-swift', :git => 'https://github.com/mixpanel/mixpanel-swift.git', :branch => 'b2b-swift'
  #pod 'HockeySDK', :subspecs => ['CrashOnlyLib']
  pod 'AppCenter', '3.3.1'
  pod 'MJRefresh'
  pod 'AlamofireImage'
  pod 'SVProgressHUD'
  pod 'Zip'
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'SwiftMessages', '~> 7.0'
  pod 'Moya', '~> 13.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ReSwift'
  pod 'PopupDialog', '~> 1.1'
  pod 'PromiseKit'
  pod 'CocoaLumberjack/Swift'
  pod 'FLEX', '4.4.0', :configurations => ['Debug']
  pod 'WaylensCarlos'
  pod 'WaylensAPNGKit', '~> 1.1'
  pod 'WaylensCameraSDK', '~> 1.1.0'
  pod 'WaylensVideoSDK', '~> 1.0.2'
  pod 'WaylensUIKit', '~> 1.0.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Parchment', '~> 3.2'
  pod "SwiftCSV"
  pod 'SSZipArchive'
  pod 'FloatingPanel', '~> 1.7.5'
  pod 'DifferenceKit'
  pod 'Charts'
  pod 'AloeStackView'
  pod 'FSCalendar'
  pod 'SwiftDate'
  pod 'Former'
  pod 'XLPagerTabStrip'
  pod 'YNDropDownMenu'
  pod "StatefulViewController", :git => 'https://github.com/YK-Unit/StatefulViewController'
  pod 'LBTATools'
  pod 'GooglePlaces'
end


target 'Fleet' do
  project 'Application/Acht.project'
  pods
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Whisper'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
